import { relations as createRelations } from "drizzle-orm";
import {
  auditLogs,
  customers,
  customerContacts,
  customerDeliveryPoints,
  cuttingResultItems,
  cuttingResults,
  factories,
  factoryConfigurations,
  fireInventoryItems,
  grindingProfiles,
  inventoryBarcodes,
  inventoryItems,
  inventoryLots,
  inventoryLocations,
  machineConsumables,
  machineMaintenance,
  machineSpareParts,
  machines,
  materials,
  materialUnitProfiles,
  orderLines,
  orderNotes,
  orders,
  permissions,
  personnel,
  emergencyContacts,
  personnelCertificates,
  personnelHealthInformation,
  personnelMachineAssignments,
  personnelShifts,
  personnelStationPermissions,
  personnelTitles,
  productCategories,
  productionBreakageEvents,
  productionEvents,
  productionOperations,
  productionOrders,
  productionQueueItems,
  productionQueues,
  products,
  recipeItems,
  recipeOperations,
  recipeRules,
  recipeVersions,
  recipes,
  remnantThresholds,
  reworkHistory,
  reworkOrders,
  rolePermissions,
  roles,
  stations,
  stationMachineAssignments,
  stationPersonnelAssignments,
  tenants,
  trimProfiles,
  userSessions,
  users,
} from "../schema/index";

const relationBuilder = createRelations;

export const relationsMap = {
  tenants: relationBuilder(tenants, ({ many }) => ({
    factories: many(factories),
    users: many(users),
    customers: many(customers),
    personnel: many(personnel),
    machines: many(machines),
    stations: many(stations),
    materials: many(materials),
    products: many(products),
    recipes: many(recipes),
    inventoryItems: many(inventoryItems),
    orders: many(orders),
    productionOrders: many(productionOrders),
    productionQueues: many(productionQueues),
    reworkOrders: many(reworkOrders),
    auditLogs: many(auditLogs),
  })),
  factories: relationBuilder(factories, ({ one, many }) => ({
    tenant: one(tenants, { fields: [factories.tenantId], references: [tenants.id] }),
    users: many(users),
    customers: many(customers),
    personnel: many(personnel),
    machines: many(machines),
    stations: many(stations),
    materials: many(materials),
    products: many(products),
    recipes: many(recipes),
    inventoryItems: many(inventoryItems),
    orders: many(orders),
    productionOrders: many(productionOrders),
    productionQueues: many(productionQueues),
    reworkOrders: many(reworkOrders),
    configurations: many(factoryConfigurations),
    grindingProfiles: many(grindingProfiles),
    trimProfiles: many(trimProfiles),
    remnantThresholds: many(remnantThresholds),
  })),
  users: relationBuilder(users, ({ one, many }) => ({
    tenant: one(tenants, { fields: [users.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [users.factoryId], references: [factories.id] }),
    selectedFactory: one(factories, { fields: [users.selectedFactoryId], references: [factories.id] }),
    role: one(roles, { fields: [users.roleId], references: [roles.id] }),
    sessions: many(userSessions),
    personnel: many(personnel),
  })),
  personnel: relationBuilder(personnel, ({ one, many }) => ({
    tenant: one(tenants, { fields: [personnel.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [personnel.factoryId], references: [factories.id] }),
    title: one(personnelTitles, { fields: [personnel.titleId], references: [personnelTitles.id] }),
    user: one(users, { fields: [personnel.userId], references: [users.id] }),
    emergencyContacts: many(emergencyContacts),
    healthInformation: many(personnelHealthInformation),
    shifts: many(personnelShifts),
    certificates: many(personnelCertificates),
    stationPermissions: many(personnelStationPermissions),
    machineAssignments: many(personnelMachineAssignments),
  })),
  stations: relationBuilder(stations, ({ one, many }) => ({
    tenant: one(tenants, { fields: [stations.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [stations.factoryId], references: [factories.id] }),
    machineAssignments: many(stationMachineAssignments),
    personnelAssignments: many(stationPersonnelAssignments),
    productionQueues: many(productionQueues),
  })),
  machines: relationBuilder(machines, ({ one, many }) => ({
    tenant: one(tenants, { fields: [machines.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [machines.factoryId], references: [factories.id] }),
    maintenanceLogs: many(machineMaintenance),
    spareParts: many(machineSpareParts),
    consumables: many(machineConsumables),
    stationAssignments: many(stationMachineAssignments),
  })),
  materials: relationBuilder(materials, ({ one, many }) => ({
    tenant: one(tenants, { fields: [materials.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [materials.factoryId], references: [factories.id] }),
    unitProfiles: many(materialUnitProfiles),
    recipeItems: many(recipeItems),
    inventoryItems: many(inventoryItems),
  })),
  products: relationBuilder(products, ({ one, many }) => ({
    tenant: one(tenants, { fields: [products.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [products.factoryId], references: [factories.id] }),
    orderLines: many(orderLines),
    inventoryItems: many(inventoryItems),
  })),
  recipes: relationBuilder(recipes, ({ one, many }) => ({
    tenant: one(tenants, { fields: [recipes.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [recipes.factoryId], references: [factories.id] }),
    items: many(recipeItems),
    operations: many(recipeOperations),
    rules: many(recipeRules),
    versions: many(recipeVersions),
    orderLines: many(orderLines),
  })),
  orders: relationBuilder(orders, ({ one, many }) => ({
    tenant: one(tenants, { fields: [orders.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [orders.factoryId], references: [factories.id] }),
    customer: one(customers, { fields: [orders.customerId], references: [customers.id] }),
    lines: many(orderLines),
    notes: many(orderNotes),
    productionOrders: many(productionOrders),
  })),
  orderLines: relationBuilder(orderLines, ({ one, many }) => ({
    order: one(orders, { fields: [orderLines.orderId], references: [orders.id] }),
    product: one(products, { fields: [orderLines.productId], references: [products.id] }),
    recipe: one(recipes, { fields: [orderLines.recipeId], references: [recipes.id] }),
    productionOrders: many(productionOrders),
  })),
  productionOrders: relationBuilder(productionOrders, ({ one, many }) => ({
    tenant: one(tenants, { fields: [productionOrders.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [productionOrders.factoryId], references: [factories.id] }),
    orderLine: one(orderLines, { fields: [productionOrders.orderLineId], references: [orderLines.id] }),
    currentStation: one(stations, { fields: [productionOrders.currentStationId], references: [stations.id] }),
    events: many(productionEvents),
    breakageEvents: many(productionBreakageEvents),
    queueItems: many(productionQueueItems),
    reworkOrders: many(reworkOrders),
  })),
  productionQueues: relationBuilder(productionQueues, ({ one, many }) => ({
    tenant: one(tenants, { fields: [productionQueues.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [productionQueues.factoryId], references: [factories.id] }),
    station: one(stations, { fields: [productionQueues.stationId], references: [stations.id] }),
    items: many(productionQueueItems),
  })),
  productionQueueItems: relationBuilder(productionQueueItems, ({ one }) => ({
    queue: one(productionQueues, { fields: [productionQueueItems.queueId], references: [productionQueues.id] }),
    productionOrder: one(productionOrders, { fields: [productionQueueItems.productionOrderId], references: [productionOrders.id] }),
  })),
  reworkOrders: relationBuilder(reworkOrders, ({ one, many }) => ({
    tenant: one(tenants, { fields: [reworkOrders.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [reworkOrders.factoryId], references: [factories.id] }),
    parentProductionOrder: one(productionOrders, { fields: [reworkOrders.parentProductionOrderId], references: [productionOrders.id] }),
    breakageEvent: one(productionBreakageEvents, { fields: [reworkOrders.breakageEventId], references: [productionBreakageEvents.id] }),
    newProductionOrder: one(productionOrders, { fields: [reworkOrders.newProductionOrderId], references: [productionOrders.id] }),
    fireInventoryItems: many(fireInventoryItems),
    history: many(reworkHistory),
  })),
  inventoryItems: relationBuilder(inventoryItems, ({ one, many }) => ({
    tenant: one(tenants, { fields: [inventoryItems.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [inventoryItems.factoryId], references: [factories.id] }),
    material: one(materials, { fields: [inventoryItems.materialId], references: [materials.id] }),
    product: one(products, { fields: [inventoryItems.productId], references: [products.id] }),
    location: one(inventoryLocations, { fields: [inventoryItems.locationId], references: [inventoryLocations.id] }),
    lots: many(inventoryLots),
    barcodes: many(inventoryBarcodes),
  })),
  inventoryLocations: relationBuilder(inventoryLocations, ({ one, many }) => ({
    tenant: one(tenants, { fields: [inventoryLocations.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [inventoryLocations.factoryId], references: [factories.id] }),
    inventoryItems: many(inventoryItems),
  })),
  inventoryLots: relationBuilder(inventoryLots, ({ one }) => ({
    item: one(inventoryItems, { fields: [inventoryLots.inventoryItemId], references: [inventoryItems.id] }),
  })),
  inventoryBarcodes: relationBuilder(inventoryBarcodes, ({ one }) => ({
    item: one(inventoryItems, { fields: [inventoryBarcodes.inventoryItemId], references: [inventoryItems.id] }),
    lot: one(inventoryLots, { fields: [inventoryBarcodes.lotId], references: [inventoryLots.id] }),
  })),
  customers: relationBuilder(customers, ({ one, many }) => ({
    tenant: one(tenants, { fields: [customers.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [customers.factoryId], references: [factories.id] }),
    contacts: many(customerContacts),
    deliveryPoints: many(customerDeliveryPoints),
    orders: many(orders),
  })),
  customerContacts: relationBuilder(customerContacts, ({ one }) => ({
    customer: one(customers, { fields: [customerContacts.customerId], references: [customers.id] }),
  })),
  customerDeliveryPoints: relationBuilder(customerDeliveryPoints, ({ one }) => ({
    customer: one(customers, { fields: [customerDeliveryPoints.customerId], references: [customers.id] }),
  })),
  auditLogs: relationBuilder(auditLogs, ({ one }) => ({
    tenant: one(tenants, { fields: [auditLogs.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [auditLogs.factoryId], references: [factories.id] }),
  })),
  roles: relationBuilder(roles, ({ many }) => ({
    users: many(users),
    rolePermissions: many(rolePermissions),
  })),
  permissions: relationBuilder(permissions, ({ many }) => ({
    rolePermissions: many(rolePermissions),
  })),
  rolePermissions: relationBuilder(rolePermissions, ({ one }) => ({
    role: one(roles, { fields: [rolePermissions.roleId], references: [roles.id] }),
    permission: one(permissions, { fields: [rolePermissions.permissionId], references: [permissions.id] }),
  })),
  personnelTitles: relationBuilder(personnelTitles, ({ many }) => ({ personnel: many(personnel) })),
  productCategories: relationBuilder(productCategories, ({ many }) => ({ products: many(products) })),
  recipeItems: relationBuilder(recipeItems, ({ one }) => ({
    recipe: one(recipes, { fields: [recipeItems.recipeId], references: [recipes.id] }),
    material: one(materials, { fields: [recipeItems.materialId], references: [materials.id] }),
  })),
  recipeOperations: relationBuilder(recipeOperations, ({ one }) => ({
    recipe: one(recipes, { fields: [recipeOperations.recipeId], references: [recipes.id] }),
  })),
  recipeRules: relationBuilder(recipeRules, ({ one }) => ({
    recipe: one(recipes, { fields: [recipeRules.recipeId], references: [recipes.id] }),
  })),
  recipeVersions: relationBuilder(recipeVersions, ({ one }) => ({
    recipe: one(recipes, { fields: [recipeVersions.recipeId], references: [recipes.id] }),
  })),
  productionEvents: relationBuilder(productionEvents, ({ one }) => ({
    productionOrder: one(productionOrders, { fields: [productionEvents.productionOrderId], references: [productionOrders.id] }),
  })),
  productionBreakageEvents: relationBuilder(productionBreakageEvents, ({ one, many }) => ({
    productionOrder: one(productionOrders, { fields: [productionBreakageEvents.productionOrderId], references: [productionOrders.id] }),
    reworkOrders: many(reworkOrders),
  })),
  cuttingResults: relationBuilder(cuttingResults, ({ one }) => ({
    tenant: one(tenants, { fields: [cuttingResults.tenantId], references: [tenants.id] }),
    factory: one(factories, { fields: [cuttingResults.factoryId], references: [factories.id] }),
    station: one(stations, { fields: [cuttingResults.stationId], references: [stations.id] }),
    machine: one(machines, { fields: [cuttingResults.machineId], references: [machines.id] }),
    operator: one(personnel, { fields: [cuttingResults.operatorId], references: [personnel.id] }),
    material: one(materials, { fields: [cuttingResults.materialId], references: [materials.id] }),
  })),
  cuttingResultItems: relationBuilder(cuttingResultItems, ({ one }) => ({
    cuttingResult: one(cuttingResults, { fields: [cuttingResultItems.cuttingResultId], references: [cuttingResults.id] }),
    productionOrder: one(productionOrders, { fields: [cuttingResultItems.productionOrderId], references: [productionOrders.id] }),
  })),
};

export const relations = relationsMap;
