// ─── Production Record Service (Sprint 6.0.0) ────────────────────────────────
// Application layer for the Production Record lifecycle.
//
// This service coordinates ProductionRecord state transitions and delegates
// all persistence to ProductionRecordRepository.
//
// It is NOT responsible for:
//   - Calculations (consumption, cost, waste, variance)
//   - Inventory updates
//   - Event publishing
//   - Recipe engine orchestration
//
// ── State Machine ────────────────────────────────────────────────────────────
//
//   PENDING (production order exists, no record yet)
//     │
//     │ openProductionRecord()
//     ▼
//   COLLECTING (data being assembled from production events)
//     │
//     │ finalizeProductionRecord()
//     ▼
//   COMPLETED (all data assembled, immutable summary)
//     │
//     │ archiveProductionRecord()
//     ▼
//   ARCHIVED (read-only historical record)
//
// Rules:
//   PENDING    → COLLECTING  ✅  (first time only — no duplicate records)
//   COLLECTING → COMPLETED   ✅  (requires quantityCompleted > 0)
//   COMPLETED  → ARCHIVED    ✅  (soft removal from active views)
//   Everything else          ❌  (rejected with descriptive error)

import {
  ProductionRecordRepository,
  ProductionRepository,
} from "../repositories/index";
import { withTenantSession } from "../db/transactions";
import { productionEvents } from "../schema/index";
import { eq } from "drizzle-orm";

import type { ProductionRecord } from "../domain/production-record.types";
import type { ProductionRecordListFilters, ProductionRecordListResult } from "../repositories/production-record.repository";

// ─── Valid Status Transitions ────────────────────────────────────────────────
// Keys = current status, values = allowed next statuses.

const VALID_TRANSITIONS: Record<string, string[]> = {
  collecting: ["completed"],
  completed: ["archived"],
  archived: [],
};

/**
 * Production Record Service — manages the lifecycle of as-built manufacturing
 * records. Every public method runs within a tenant-scoped transaction.
 */
export class ProductionRecordService {
  constructor(
    private readonly productionRecordRepository: ProductionRecordRepository,
    private readonly productionRepository: ProductionRepository,
    private readonly db: any,
  ) {}

  /* ══════════════════════════════════════════════════════════════════════════
     OPEN
     ══════════════════════════════════════════════════════════════════════════ */

  /**
   * Open a new Production Record for a Production Order.
   *
   * Transition: PENDING → COLLECTING
   *
   * Validations:
   *   1. Production Order must exist.
   *   2. No Production Record must already exist for this order.
   *   3. A ULID must be provided (generated by the caller).
   *
   * The record is created in `collecting` status. All performance summary
   * fields default to zero/null — they are populated during finalization.
   *
   * @param input.id - ULID for the new record (caller-generated)
   * @param input.productionOrderId - ULID of the existing Production Order
   * @param input.recipeId - ULID of the recipe (optional, for snapshot)
   * @param input.recipeVersion - Recipe version at time of production
   * @param options.userId - ULID of the user performing this action
   * @returns The newly created Production Record
   * @throws Error if production order missing, or record already exists
   */
  async openProductionRecord(
    input: {
      id: string;
      productionOrderId: string;
      recipeId?: string;
      recipeVersion: number;
    },
    options: { userId?: string } = {},
  ): Promise<ProductionRecord> {
    return withTenantSession(async (tx, ctx) => {
      // ── Validation 1: Production Order must exist ──────────────────────
      const prodOrder = await this.productionRepository.findById(
        input.productionOrderId,
      );
      if (!prodOrder) {
        throw new Error(
          `Cannot open production record: Production order not found: ${input.productionOrderId}`,
        );
      }

      // ── Validation 2: No duplicate record ──────────────────────────────
      const existing = await this.productionRecordRepository.findByProductionOrderId(
        input.productionOrderId,
      );
      if (existing) {
        throw new Error(
          `Cannot open production record: A record already exists for production order ${input.productionOrderId} (status: ${existing.status})`,
        );
      }

      // ── Validation 3: ULID is required ─────────────────────────────────
      if (!input.id || input.id.length !== 26) {
        throw new Error(
          `Cannot open production record: A valid 26-character ULID is required`,
        );
      }

      // ── Create the record in COLLECTING status ─────────────────────────
      return this.productionRecordRepository.create({
        id: input.id,
        tenantId: ctx.tenantId!,
        factoryId: ctx.factoryId,
        productionOrderId: input.productionOrderId,
        productType: (prodOrder as any).productType ?? undefined,
        businessWidthMm: String((prodOrder as any).widthMm ?? ""),
        businessHeightMm: String((prodOrder as any).heightMm ?? ""),
        quantityRequested: Number((prodOrder as any).quantity ?? 0),
        recipeId: input.recipeId,
        recipeVersion: input.recipeVersion,
        createdBy: options.userId,
      });
    });
  }

  /* ══════════════════════════════════════════════════════════════════════════
     FINALIZE
     ══════════════════════════════════════════════════════════════════════════ */

  /**
   * Finalize a Production Record — transition from COLLECTING to COMPLETED.
   *
   * Validations:
   *   1. Record must exist.
   *   2. Record must be in `collecting` status.
   *   3. quantityCompleted must be > 0 (a production run produced something).
   *   4. Completed records are immutable — further updates rejected.
   *
   * On success, the record is locked. Summary fields become immutable.
   * JSONB value objects (consumption, analysis) follow their own
   * immutability rules documented in the domain model.
   *
   * @param id - ULID of the Production Record to finalize
   * @param input.quantityCompleted - Total pieces successfully produced
   * @param input.quantityBroken - Total pieces broken during production
   * @param input.totalSheetsUsed - Total glass sheets consumed (optional)
   * @param options.userId - ULID of the user finalizing this record
   * @returns The finalized Production Record
   * @throws Error if record not found, wrong status, or zero completed
   */
  async finalizeProductionRecord(
    id: string,
    input: {
      quantityCompleted: number;
      quantityBroken?: number;
      totalSheetsUsed?: number;
      totalGlassAreaM2?: string;
      totalWasteM2?: string;
      yieldPercentage?: string;
      totalCost?: string;
      consumptionDetails?: any;
      analysisDetails?: any;
      traceability?: any;
    },
    options: { userId?: string } = {},
  ): Promise<ProductionRecord> {
    return withTenantSession(async (tx, ctx) => {
      // ── Validation 1: Record must exist ────────────────────────────────
      const existing = await this.productionRecordRepository.findById(id);
      if (!existing) {
        throw new Error(
          `Cannot finalize production record: Record not found: ${id}`,
        );
      }

      // ── Validation 2: Must be in COLLECTING status ─────────────────────
      if (existing.status !== "collecting") {
        throw new Error(
          `Cannot finalize production record ${id}: Current status is "${existing.status}". ` +
          `Only records in "collecting" status can be finalized.`,
        );
      }

      // ── Validation 3: Must have produced something ─────────────────────
      if (input.quantityCompleted <= 0) {
        throw new Error(
          `Cannot finalize production record ${id}: quantityCompleted must be greater than 0. ` +
          `Received: ${input.quantityCompleted}.`,
        );
      }

      // ── Finalize ───────────────────────────────────────────────────────
      return this.productionRecordRepository.update(id, {
        status: "completed",
        quantityCompleted: input.quantityCompleted,
        quantityBroken: input.quantityBroken ?? 0,
        totalSheetsUsed: input.totalSheetsUsed,
        totalGlassAreaM2: input.totalGlassAreaM2,
        totalWasteM2: input.totalWasteM2,
        yieldPercentage: input.yieldPercentage,
        totalCost: input.totalCost,
        consumptionDetails: input.consumptionDetails,
        analysisDetails: input.analysisDetails,
        traceability: input.traceability,
        completedAt: new Date().toISOString(),
        completedBy: options.userId,
        updatedBy: options.userId,
      });
    });
  }

  /* ══════════════════════════════════════════════════════════════════════════
     ARCHIVE
     ══════════════════════════════════════════════════════════════════════════ */

  /**
   * Archive a Production Record — transition from COMPLETED to ARCHIVED.
   *
   * Validations:
   *   1. Record must exist.
   *   2. Record must be in `completed` status.
   *   3. Archived records are read-only.
   *
   * Archiving soft-removes the record from active list views while
   * preserving it for historical and audit purposes.
   *
   * @param id - ULID of the Production Record to archive
   * @param options.userId - ULID of the user performing this action
   * @returns The archived Production Record
   * @throws Error if record not found or not in completed status
   */
  async archiveProductionRecord(
    id: string,
    options: { userId?: string } = {},
  ): Promise<ProductionRecord> {
    return withTenantSession(async (tx, ctx) => {
      // ── Validation 1: Record must exist ────────────────────────────────
      const existing = await this.productionRecordRepository.findById(id);
      if (!existing) {
        throw new Error(
          `Cannot archive production record: Record not found: ${id}`,
        );
      }

      // ── Validation 2: Must be in COMPLETED status ──────────────────────
      if (existing.status !== "completed") {
        throw new Error(
          `Cannot archive production record ${id}: Current status is "${existing.status}". ` +
          `Only records in "completed" status can be archived.`,
        );
      }

      // ── Archive ────────────────────────────────────────────────────────
      return this.productionRecordRepository.update(id, {
        status: "archived",
        updatedBy: options.userId,
      });
    });
  }

  /* ══════════════════════════════════════════════════════════════════════════
     READERS
     ══════════════════════════════════════════════════════════════════════════ */

  /**
   * Get a Production Record by its ULID.
   *
   * @param id - ULID of the Production Record
   * @returns The Production Record, or undefined if not found
   */
  async getById(id: string): Promise<ProductionRecord | undefined> {
    return withTenantSession(async (tx, ctx) => {
      return this.productionRecordRepository.findById(id);
    });
  }

  /**
   * Get a Production Record by its Production Order ID.
   *
   * @param productionOrderId - ULID of the Production Order
   * @returns The Production Record, or undefined if not found
   */
  async getByProductionOrderId(
    productionOrderId: string,
  ): Promise<ProductionRecord | undefined> {
    return withTenantSession(async (tx, ctx) => {
      return this.productionRecordRepository.findByProductionOrderId(
        productionOrderId,
      );
    });
  }

  /**
   * List Production Records with filtering and pagination.
   *
   * Supported filters:
   *   - status: Filter by record status (collecting, completed, archived)
   *   - productType: Filter by product type
   *   - productionOrderId: Filter by production order
   *   - recipeId: Filter by recipe
   *   - completedBy: Filter by user who completed the record
   *   - search: ILIKE search on productType and id
   *   - startDate / endDate: Date range filter on createdAt
   *   - sortBy / sortOrder: Sort column and direction (default: createdAt desc)
   *
   * @param filters - Optional filter and pagination parameters
   * @returns Paginated list of Production Records
   */
  async list(
    filters?: ProductionRecordListFilters,
  ): Promise<ProductionRecordListResult> {
    return withTenantSession(async (tx, ctx) => {
      return this.productionRecordRepository.findForList(
        ctx.tenantId!,
        filters,
      );
    });
  }

  /**
   * Check if a Production Record exists by its ULID.
   *
   * @param id - ULID of the Production Record
   * @returns True if the record exists
   */
  async exists(id: string): Promise<boolean> {
    return withTenantSession(async (tx, ctx) => {
      return this.productionRecordRepository.exists(id);
    });
  }

  /* ══════════════════════════════════════════════════════════════════════════
     INTEGRATION — Production Order Completion Hook
     ══════════════════════════════════════════════════════════════════════════ */

  /**
   * Handle production order completion — automatically creates and finalizes
   * a Production Record when a Production Order reaches "completed" status.
   *
   * Idempotent: If a Production Record already exists for this production
   * order, the method returns `null` — no duplicate is created.
   *
   * Flow:
   *   1. Idempotency check — skip if record exists
   *   2. Validate production order exists
   *   3. Generate ULID for the new record
   *   4. Gather production events for basic quantity data
   *   5. Open Production Record → COLLECTING
   *   6. Finalize Production Record → COMPLETED
   *
   * NOTE: This method does NOT calculate cost, consumption, waste, or
   * variance. Those values are placeholders to be populated by future
   * engines (Sprint 6.1.0+).
   *
   * @param productionOrderId - ULID of the completed Production Order
   * @param options.userId - ULID of the user who completed the order
   * @returns The finalized Production Record, or null if already exists
   */
  async handleProductionCompletion(
    productionOrderId: string,
    options: { userId?: string } = {},
  ): Promise<ProductionRecord | null> {
    // Run inside withTenantSession to ensure RLS context is available for
    // all repository reads. Inner calls (openProductionRecord,
    // finalizeProductionRecord) each start their own transaction
    // (PostgreSQL savepoints), which is fully supported.
    return withTenantSession(async (_tx, ctx) => {
      // ── Step 1: Idempotency check ─────────────────────────────────────
      // If a record already exists, the integration is idempotent — skip.
      // This prevents duplicates when both the direct API and queue
      // completion paths are triggered for the same production order.
      const existing =
        await this.productionRecordRepository.findByProductionOrderId(
          productionOrderId,
        );
      if (existing) {
        return null;
      }

      // ── Step 2: Validate production order exists ──────────────────────
      const prodOrder = await this.productionRepository.findById(
        productionOrderId,
      );
      if (!prodOrder) {
        throw new Error(
          `Cannot create production record: Production order not found: ${productionOrderId}`,
        );
      }

      // ── Step 3: Generate ULID for the new record ──────────────────────
      const recordId = this._generateUlid();

      // ── Step 4: Read production events for basic quantity data ────────
      // Count station-level "completed" events as a proxy for production
      // progress. Future engines will replace this with precise tracking.
      const events = await this.db
        .select()
        .from(productionEvents)
        .where(eq(productionEvents.productionOrderId, productionOrderId))
        .execute();
      const completedEvents = (events as any[]).filter(
        (e: any) => e.eventType === "completed",
      );
      const brokenEvents = (events as any[]).filter(
        (e: any) => e.eventType === "broken",
      );

      // ── Step 5: Open → COLLECTING ─────────────────────────────────────
      // Uses its own withTenantSession (savepoint inside outer tx)
      await this.openProductionRecord(
        {
          id: recordId,
          productionOrderId,
          recipeId: (prodOrder as any).recipeId ?? undefined,
          recipeVersion: (prodOrder as any).recipeVersion ?? 1,
        },
        { userId: options.userId },
      );

      // ── Step 6: Finalize → COMPLETED ──────────────────────────────────
      // At least 1 is used for quantityCompleted so the record is
      // meaningful even when no events have been explicitly recorded.
      return this.finalizeProductionRecord(
        recordId,
        {
          quantityCompleted: Math.max(completedEvents.length, 1),
          quantityBroken: brokenEvents.length,
        },
        { userId: options.userId },
      );
    });
  }

  // ─── Internal Helpers ─────────────────────────────────────────────────────

  /**
   * Generate a Crockford Base32 ULID using the current timestamp.
   * Matches the 26-character format validated by the ULID schema.
   */
  private _generateUlid(): string {
    const CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
    const timestamp = Date.now();

    // Encode 48-bit timestamp as 10 Crockford base32 characters
    let timeStr = "";
    let t = timestamp;
    for (let i = 0; i < 10; i++) {
      timeStr = CROCKFORD[t & 0x1f] + timeStr;
      t >>>= 5;
    }

    // Generate 16 random characters (80 bits of entropy)
    let randomStr = "";
    for (let i = 0; i < 16; i++) {
      randomStr += CROCKFORD[Math.floor(Math.random() * 32)];
    }

    return timeStr + randomStr;
  }
}
