/**
 * Turkish cities and districts data.
 * All 81 provinces with their districts — complete and accurate for reporting.
 */

export interface District {
  value: string;
  label: string;
}

export interface City {
  value: string;
  label: string;
  districts: District[];
}

/** All 81 Turkish cities (provinces) with their official districts. */
export const TURKEY_CITIES: City[] = [
  {
    value: "adana",
    label: "Adana",
    districts: [
      { value: "aladag", label: "Aladağ" },
      { value: "ceyhan", label: "Ceyhan" },
      { value: "cukurova", label: "Çukurova" },
      { value: "feke", label: "Feke" },
      { value: "imamoglu", label: "İmamoğlu" },
      { value: "karaisali", label: "Karaisalı" },
      { value: "karatas", label: "Karataş" },
      { value: "kozan", label: "Kozan" },
      { value: "pozanti", label: "Pozantı" },
      { value: "saimbeyli", label: "Saimbeyli" },
      { value: "saricam", label: "Sarıçam" },
      { value: "seyhan", label: "Seyhan" },
      { value: "tufanbeyli", label: "Tufanbeyli" },
      { value: "yumurtalik", label: "Yumurtalık" },
      { value: "yuregir", label: "Yüreğir" },
    ],
  },
  {
    value: "adiyaman",
    label: "Adıyaman",
    districts: [
      { value: "besni", label: "Besni" },
      { value: "celikhan", label: "Çelikhan" },
      { value: "gerger", label: "Gerger" },
      { value: "golbasi", label: "Gölbaşı" },
      { value: "kahta", label: "Kahta" },
      { value: "merkez", label: "Merkez" },
      { value: "samsat", label: "Samsat" },
      { value: "sincik", label: "Sincik" },
      { value: "tut", label: "Tut" },
    ],
  },
  {
    value: "afyonkarahisar",
    label: "Afyonkarahisar",
    districts: [
      { value: "basmakci", label: "Başmakçı" },
      { value: "bayat", label: "Bayat" },
      { value: "bolvadin", label: "Bolvadin" },
      { value: "cay", label: "Çay" },
      { value: "cobanlar", label: "Çobanlar" },
      { value: "dazkiri", label: "Dazkırı" },
      { value: "dinar", label: "Dinar" },
      { value: "emirdag", label: "Emirdağ" },
      { value: "evciler", label: "Evciler" },
      { value: "hocalar", label: "Hocalar" },
      { value: "ihsaniye", label: "İhsaniye" },
      { value: "iscehisar", label: "İscehisar" },
      { value: "kiziloren", label: "Kızılören" },
      { value: "merkez", label: "Merkez" },
      { value: "sandikli", label: "Sandıklı" },
      { value: "sinanpasa", label: "Sinanpaşa" },
      { value: "suhut", label: "Şuhut" },
      { value: "sultandagi", label: "Sultandağı" },
    ],
  },
  {
    value: "agri",
    label: "Ağrı",
    districts: [
      { value: "diyadin", label: "Diyadin" },
      { value: "dogubayazit", label: "Doğubayazıt" },
      { value: "eleskirt", label: "Eleşkirt" },
      { value: "hamur", label: "Hamur" },
      { value: "merkez", label: "Merkez" },
      { value: "patnos", label: "Patnos" },
      { value: "taslicay", label: "Taşlıçay" },
      { value: "tutak", label: "Tutak" },
    ],
  },
  {
    value: "amasya",
    label: "Amasya",
    districts: [
      { value: "goynucek", label: "Göynücek" },
      { value: "gumushacikoy", label: "Gümüşhacıköy" },
      { value: "hamamozu", label: "Hamamözü" },
      { value: "merkez", label: "Merkez" },
      { value: "merzifon", label: "Merzifon" },
      { value: "suluova", label: "Suluova" },
      { value: "tasova", label: "Taşova" },
    ],
  },
  {
    value: "ankara",
    label: "Ankara",
    districts: [
      { value: "akyurt", label: "Akyurt" },
      { value: "altindag", label: "Altındağ" },
      { value: "ayas", label: "Ayaş" },
      { value: "bala", label: "Balâ" },
      { value: "beypazari", label: "Beypazarı" },
      { value: "camlidere", label: "Çamlıdere" },
      { value: "cankaya", label: "Çankaya" },
      { value: "cubuk", label: "Çubuk" },
      { value: "elmadag", label: "Elmadağ" },
      { value: "etimesgut", label: "Etimesgut" },
      { value: "evren", label: "Evren" },
      { value: "golbasi", label: "Gölbaşı" },
      { value: "gudul", label: "Güdül" },
      { value: "haymana", label: "Haymana" },
      { value: "kahramankazan", label: "Kahramankazan" },
      { value: "kalecik", label: "Kalecik" },
      { value: "kecioren", label: "Keçiören" },
      { value: "kizilcahamam", label: "Kızılcahamam" },
      { value: "mamak", label: "Mamak" },
      { value: "nallihan", label: "Nallıhan" },
      { value: "polatli", label: "Polatlı" },
      { value: "pursaklar", label: "Pursaklar" },
      { value: "sereflikochisar", label: "Şereflikoçhisar" },
      { value: "sincan", label: "Sincan" },
      { value: "yenimahalle", label: "Yenimahalle" },
    ],
  },
  {
    value: "antalya",
    label: "Antalya",
    districts: [
      { value: "akseki", label: "Akseki" },
      { value: "aksu", label: "Aksu" },
      { value: "alanya", label: "Alanya" },
      { value: "demre", label: "Demre" },
      { value: "dosemealti", label: "Döşemealtı" },
      { value: "elmali", label: "Elmalı" },
      { value: "finike", label: "Finike" },
      { value: "gazipasa", label: "Gazipaşa" },
      { value: "gundogmus", label: "Gündoğmuş" },
      { value: "ibradi", label: "İbradı" },
      { value: "kale", label: "Kale" },
      { value: "kas", label: "Kaş" },
      { value: "kemer", label: "Kemer" },
      { value: "konyaalti", label: "Konyaaltı" },
      { value: "korkuteli", label: "Korkuteli" },
      { value: "kumluca", label: "Kumluca" },
      { value: "manavgat", label: "Manavgat" },
      { value: "muratpasa", label: "Muratpaşa" },
      { value: "serik", label: "Serik" },
    ],
  },
  {
    value: "artvin",
    label: "Artvin",
    districts: [
      { value: "ardanuc", label: "Ardanuç" },
      { value: "arhavi", label: "Arhavi" },
      { value: "borcka", label: "Borçka" },
      { value: "hopa", label: "Hopa" },
      { value: "kemalpasa", label: "Kemalpaşa" },
      { value: "merkez", label: "Merkez" },
      { value: "murgul", label: "Murgul" },
      { value: "savsat", label: "Şavşat" },
      { value: "yusufeli", label: "Yusufeli" },
    ],
  },
  {
    value: "aydin",
    label: "Aydın",
    districts: [
      { value: "bozdogan", label: "Bozdoğan" },
      { value: "buharkent", label: "Buharkent" },
      { value: "cine", label: "Çine" },
      { value: "didim", label: "Didim" },
      { value: "efeler", label: "Efeler" },
      { value: "germencik", label: "Germencik" },
      { value: "incirliova", label: "İncirliova" },
      { value: "karacasu", label: "Karacasu" },
      { value: "karpuzlu", label: "Karpuzlu" },
      { value: "kocarli", label: "Koçarlı" },
      { value: "kosk", label: "Köşk" },
      { value: "kusadasi", label: "Kuşadası" },
      { value: "kuyucak", label: "Kuyucak" },
      { value: "nazilli", label: "Nazilli" },
      { value: "soke", label: "Söke" },
      { value: "sultanhisar", label: "Sultanhisar" },
      { value: "yenipazar", label: "Yenipazar" },
    ],
  },
  {
    value: "balikesir",
    label: "Balıkesir",
    districts: [
      { value: "altieylul", label: "Altıeylül" },
      { value: "ayvalik", label: "Ayvalık" },
      { value: "balya", label: "Balya" },
      { value: "bandirma", label: "Bandırma" },
      { value: "bigadic", label: "Bigadiç" },
      { value: "burhaniye", label: "Burhaniye" },
      { value: "dursunbey", label: "Dursunbey" },
      { value: "edremit", label: "Edremit" },
      { value: "erdemit", label: "Erdek" },
      { value: "gomec", label: "Gömeç" },
      { value: "gonen", label: "Gönen" },
      { value: "havran", label: "Havran" },
      { value: "ivrindi", label: "İvrindi" },
      { value: "karesi", label: "Karesi" },
      { value: "kepsut", label: "Kepsut" },
      { value: "manyas", label: "Manyas" },
      { value: "marmara", label: "Marmara" },
      { value: "savastepe", label: "Savaştepe" },
      { value: "sindirgi", label: "Sındırgı" },
      { value: "susurluk", label: "Susurluk" },
    ],
  },
  {
    value: "bilecik",
    label: "Bilecik",
    districts: [
      { value: "bozuyuk", label: "Bozüyük" },
      { value: "golpazari", label: "Gölpazarı" },
      { value: "inhisar", label: "İnhisar" },
      { value: "merkez", label: "Merkez" },
      { value: "osmaneli", label: "Osmaneli" },
      { value: "pazaryeri", label: "Pazaryeri" },
      { value: "sogut", label: "Söğüt" },
      { value: "yenipazar", label: "Yenipazar" },
    ],
  },
  {
    value: "bingol",
    label: "Bingöl",
    districts: [
      { value: "adagli", label: "Adaklı" },
      { value: "genc", label: "Genç" },
      { value: "karliova", label: "Karlıova" },
      { value: "kigi", label: "Kiğı" },
      { value: "merkez", label: "Merkez" },
      { value: "solhan", label: "Solhan" },
      { value: "yayladere", label: "Yayladere" },
      { value: "yedisu", label: "Yedisu" },
    ],
  },
  {
    value: "bitlis",
    label: "Bitlis",
    districts: [
      { value: "adilcevaz", label: "Adilcevaz" },
      { value: "ahlat", label: "Ahlat" },
      { value: "guroymak", label: "Güroymak" },
      { value: "hizan", label: "Hizan" },
      { value: "merkez", label: "Merkez" },
      { value: "mutki", label: "Mutki" },
      { value: "tatvan", label: "Tatvan" },
    ],
  },
  {
    value: "bolu",
    label: "Bolu",
    districts: [
      { value: "dortdivan", label: "Dörtdivan" },
      { value: "gerede", label: "Gerede" },
      { value: "goynuk", label: "Göynük" },
      { value: "kibriscik", label: "Kıbrıscık" },
      { value: "mengen", label: "Mengen" },
      { value: "merkez", label: "Merkez" },
      { value: "mudurnu", label: "Mudurnu" },
      { value: "seben", label: "Seben" },
      { value: "yeniceaga", label: "Yeniçağa" },
    ],
  },
  {
    value: "burdur",
    label: "Burdur",
    districts: [
      { value: "aglasun", label: "Ağlasun" },
      { value: "altinyayla", label: "Altınyayla" },
      { value: "bucak", label: "Bucak" },
      { value: "cavdir", label: "Çavdır" },
      { value: "celtikci", label: "Çeltikçi" },
      { value: "golhisar", label: "Gölhisar" },
      { value: "karamanli", label: "Karamanlı" },
      { value: "kemer", label: "Kemer" },
      { value: "merkez", label: "Merkez" },
      { value: "tefenni", label: "Tefenni" },
      { value: "yesilova", label: "Yeşilova" },
    ],
  },
  {
    value: "bursa",
    label: "Bursa",
    districts: [
      { value: "buyukorhan", label: "Büyükorhan" },
      { value: "gemlik", label: "Gemlik" },
      { value: "gursu", label: "Gürsu" },
      { value: "harmancik", label: "Harmancık" },
      { value: "inegol", label: "İnegöl" },
      { value: "iznik", label: "İznik" },
      { value: "karacabey", label: "Karacabey" },
      { value: "keles", label: "Keles" },
      { value: "kestel", label: "Kestel" },
      { value: "mudanya", label: "Mudanya" },
      { value: "mustafakemalpasa", label: "Mustafakemalpaşa" },
      { value: "nilufer", label: "Nilüfer" },
      { value: "orhaneli", label: "Orhaneli" },
      { value: "orangazi", label: "Orhangazi" },
      { value: "osmangazi", label: "Osmangazi" },
      { value: "yenisehir", label: "Yenişehir" },
      { value: "yildirim", label: "Yıldırım" },
    ],
  },
  {
    value: "canakkale",
    label: "Çanakkale",
    districts: [
      { value: "ayvacik", label: "Ayvacık" },
      { value: "bayramic", label: "Bayramiç" },
      { value: "biga", label: "Biga" },
      { value: "bozcaada", label: "Bozcaada" },
      { value: "can", label: "Çan" },
      { value: "eceabat", label: "Eceabat" },
      { value: "ezine", label: "Ezine" },
      { value: "gelibolu", label: "Gelibolu" },
      { value: "gokceada", label: "Gökçeada" },
      { value: "lapseki", label: "Lapseki" },
      { value: "merkez", label: "Merkez" },
      { value: "yenice", label: "Yenice" },
    ],
  },
  {
    value: "cankiri",
    label: "Çankırı",
    districts: [
      { value: "atkaracalar", label: "Atkaracalar" },
      { value: "bayramoren", label: "Bayramören" },
      { value: "cerkes", label: "Çerkeş" },
      { value: "eldivan", label: "Eldivan" },
      { value: "ilgaz", label: "Ilgaz" },
      { value: "kizilirmak", label: "Kızılırmak" },
      { value: "korgun", label: "Korgun" },
      { value: "kursunlu", label: "Kurşunlu" },
      { value: "merkez", label: "Merkez" },
      { value: "orta", label: "Orta" },
      { value: "sabanonu", label: "Şabanözü" },
      { value: "yaprakli", label: "Yapraklı" },
    ],
  },
  {
    value: "corum",
    label: "Çorum",
    districts: [
      { value: "alaca", label: "Alaca" },
      { value: "bayat", label: "Bayat" },
      { value: "bogazkale", label: "Boğazkale" },
      { value: "dodurga", label: "Dodurga" },
      { value: "iskilip", label: "İskilip" },
      { value: "kargi", label: "Kargı" },
      { value: "lacin", label: "Laçin" },
      { value: "mecitozu", label: "Mecitözü" },
      { value: "merkez", label: "Merkez" },
      { value: "oguzlar", label: "Oğuzlar" },
      { value: "ortakoy", label: "Ortaköy" },
      { value: "osmancik", label: "Osmancık" },
      { value: "sungurlu", label: "Sungurlu" },
      { value: "ugurludag", label: "Uğurludağ" },
    ],
  },
  {
    value: "denizli",
    label: "Denizli",
    districts: [
      { value: "acipayam", label: "Acıpayam" },
      { value: "babadag", label: "Babadağ" },
      { value: "baklan", label: "Baklan" },
      { value: "bekilli", label: "Bekilli" },
      { value: "beyagac", label: "Beyağaç" },
      { value: "bozkurt", label: "Bozkurt" },
      { value: "buldan", label: "Buldan" },
      { value: "cal", label: "Çal" },
      { value: "cameli", label: "Çameli" },
      { value: "cardak", label: "Çardak" },
      { value: "civril", label: "Çivril" },
      { value: "guney", label: "Güney" },
      { value: "honaz", label: "Honaz" },
      { value: "kale", label: "Kale" },
      { value: "merkezefendi", label: "Merkezefendi" },
      { value: "pamukkale", label: "Pamukkale" },
      { value: "saraykoy", label: "Sarayköy" },
      { value: "serinhisar", label: "Serinhisar" },
      { value: "tavas", label: "Tavas" },
    ],
  },
  {
    value: "diyarbakir",
    label: "Diyarbakır",
    districts: [
      { value: "baglar", label: "Bağlar" },
      { value: "bismil", label: "Bismil" },
      { value: "cermik", label: "Çermik" },
      { value: "cinar", label: "Çınar" },
      { value: "cungus", label: "Çüngüş" },
      { value: "dicle", label: "Dicle" },
      { value: "egil", label: "Eğil" },
      { value: "ergani", label: "Ergani" },
      { value: "hani", label: "Hani" },
      { value: "hazro", label: "Hazro" },
      { value: "kayapinar", label: "Kayapınar" },
      { value: "kocakoy", label: "Kocaköy" },
      { value: "kulp", label: "Kulp" },
      { value: "lice", label: "Lice" },
      { value: "silvan", label: "Silvan" },
      { value: "sur", label: "Sur" },
      { value: "yenisehir", label: "Yenişehir" },
    ],
  },
  {
    value: "edirne",
    label: "Edirne",
    districts: [
      { value: "enez", label: "Enez" },
      { value: "havsa", label: "Havsa" },
      { value: "ipsala", label: "İpsala" },
      { value: "kesan", label: "Keşan" },
      { value: "lalapasa", label: "Lalapaşa" },
      { value: "meric", label: "Meriç" },
      { value: "merkez", label: "Merkez" },
      { value: "suloglu", label: "Süloğlu" },
      { value: "uzunkopru", label: "Uzunköprü" },
    ],
  },
  {
    value: "elazig",
    label: "Elazığ",
    districts: [
      { value: "agin", label: "Ağın" },
      { value: "alacakaya", label: "Alacakaya" },
      { value: "aricak", label: "Arıcak" },
      { value: "baskil", label: "Baskil" },
      { value: "karakocan", label: "Karakoçan" },
      { value: "keban", label: "Keban" },
      { value: "kovancilar", label: "Kovancılar" },
      { value: "maden", label: "Maden" },
      { value: "merkez", label: "Merkez" },
      { value: "palu", label: "Palu" },
      { value: "sivrice", label: "Sivrice" },
    ],
  },
  {
    value: "erzincan",
    label: "Erzincan",
    districts: [
      { value: "cayirli", label: "Çayırlı" },
      { value: "ilic", label: "İliç" },
      { value: "kemah", label: "Kemah" },
      { value: "kemaliye", label: "Kemaliye" },
      { value: "merkez", label: "Merkez" },
      { value: "otlukbeli", label: "Otlukbeli" },
      { value: "refahiye", label: "Refahiye" },
      { value: "tercan", label: "Tercan" },
      { value: "uzumlu", label: "Üzümlü" },
    ],
  },
  {
    value: "erzurum",
    label: "Erzurum",
    districts: [
      { value: "askale", label: "Aşkale" },
      { value: "aziziye", label: "Aziziye" },
      { value: "cat", label: "Çat" },
      { value: "hinis", label: "Hınıs" },
      { value: "horasan", label: "Horasan" },
      { value: "ispir", label: "İspir" },
      { value: "karacoban", label: "Karaçoban" },
      { value: "karayazi", label: "Karayazı" },
      { value: "koprukoy", label: "Köprüköy" },
      { value: "narman", label: "Narman" },
      { value: "oltu", label: "Oltu" },
      { value: "olur", label: "Olur" },
      { value: "palandoken", label: "Palandöken" },
      { value: "pasinler", label: "Pasinler" },
      { value: "pazaryolu", label: "Pazaryolu" },
      { value: "senkaya", label: "Şenkaya" },
      { value: "tekman", label: "Tekman" },
      { value: "tortum", label: "Tortum" },
      { value: "uzundere", label: "Uzundere" },
      { value: "yakutiye", label: "Yakutiye" },
    ],
  },
  {
    value: "eskisehir",
    label: "Eskişehir",
    districts: [
      { value: "alpu", label: "Alpu" },
      { value: "beylikova", label: "Beylikova" },
      { value: "cifteler", label: "Çifteler" },
      { value: "gunyuzu", label: "Günyüzü" },
      { value: "han", label: "Han" },
      { value: "inonu", label: "İnönü" },
      { value: "mahmudiye", label: "Mahmudiye" },
      { value: "mihalgazi", label: "Mihalgazi" },
      { value: "mihaliccik", label: "Mihalıççık" },
      { value: "odunpazari", label: "Odunpazarı" },
      { value: "sariz", label: "Sarıcakaya" },
      { value: "seyitgazi", label: "Seyitgazi" },
      { value: "sivrihisar", label: "Sivrihisar" },
      { value: "tepebasi", label: "Tepebaşı" },
    ],
  },
  {
    value: "gaziantep",
    label: "Gaziantep",
    districts: [
      { value: "araban", label: "Araban" },
      { value: "islahiye", label: "İslahiye" },
      { value: "karkamis", label: "Karkamış" },
      { value: "nizip", label: "Nizip" },
      { value: "nurdagi", label: "Nurdağı" },
      { value: "oguzeli", label: "Oğuzeli" },
      { value: "sahinbey", label: "Şahinbey" },
      { value: "sehitkamil", label: "Şehitkamil" },
      { value: "yavuzeli", label: "Yavuzeli" },
    ],
  },
  {
    value: "giresun",
    label: "Giresun",
    districts: [
      { value: "alucra", label: "Alucra" },
      { value: "bulancak", label: "Bulancak" },
      { value: "camoluk", label: "Çamoluk" },
      { value: "canakci", label: "Çanakçı" },
      { value: "dereli", label: "Dereli" },
      { value: "dogankent", label: "Doğankent" },
      { value: "espiye", label: "Espiye" },
      { value: "eynesil", label: "Eynesil" },
      { value: "gorele", label: "Görele" },
      { value: "guce", label: "Güce" },
      { value: "kesap", label: "Keşap" },
      { value: "merkez", label: "Merkez" },
      { value: "piraziz", label: "Piraziz" },
      { value: "sebinkarahisar", label: "Şebinkarahisar" },
      { value: "tirebolu", label: "Tirebolu" },
      { value: "yaglidere", label: "Yağlıdere" },
    ],
  },
  {
    value: "gumushane",
    label: "Gümüşhane",
    districts: [
      { value: "kelkit", label: "Kelkit" },
      { value: "kose", label: "Köse" },
      { value: "kurtun", label: "Kürtün" },
      { value: "merkez", label: "Merkez" },
      { value: "siran", label: "Şiran" },
      { value: "torul", label: "Torul" },
    ],
  },
  {
    value: "hakkari",
    label: "Hakkâri",
    districts: [
      { value: "cukurca", label: "Çukurca" },
      { value: "derecik", label: "Derecik" },
      { value: "merkez", label: "Merkez" },
      { value: "semdinli", label: "Şemdinli" },
      { value: "yuksekova", label: "Yüksekova" },
    ],
  },
  {
    value: "hatay",
    label: "Hatay",
    districts: [
      { value: "altinozu", label: "Altınözü" },
      { value: "antakya", label: "Antakya" },
      { value: "arsuz", label: "Arsuz" },
      { value: "belen", label: "Belen" },
      { value: "defne", label: "Defne" },
      { value: "dortyol", label: "Dörtyol" },
      { value: "erzin", label: "Erzin" },
      { value: "hassa", label: "Hassa" },
      { value: "iskenderun", label: "İskenderun" },
      { value: "kirikhan", label: "Kırıkhan" },
      { value: "kumlu", label: "Kumlu" },
      { value: "payas", label: "Payas" },
      { value: "reyhanli", label: "Reyhanlı" },
      { value: "samandag", label: "Samandağ" },
      { value: "yayladagi", label: "Yayladağı" },
    ],
  },
  {
    value: "isparta",
    label: "Isparta",
    districts: [
      { value: "aksu", label: "Aksu" },
      { value: "atabey", label: "Atabey" },
      { value: "egirdir", label: "Eğirdir" },
      { value: "gelendost", label: "Gelendost" },
      { value: "gonen", label: "Gönen" },
      { value: "keciborlu", label: "Keçiborlu" },
      { value: "merkez", label: "Merkez" },
      { value: "senirkent", label: "Senirkent" },
      { value: "sutculer", label: "Sütçüler" },
      { value: "sarkikaraagac", label: "Şarkikaraağaç" },
      { value: "uluborlu", label: "Uluborlu" },
      { value: "yalvac", label: "Yalvaç" },
      { value: "enisarbademli", label: "Yenişarbademli" },
    ],
  },
  {
    value: "mersin",
    label: "Mersin",
    districts: [
      { value: "akdeniz", label: "Akdeniz" },
      { value: "anmur", label: "Anamur" },
      { value: "aydncik", label: "Aydıncık" },
      { value: "bozyazi", label: "Bozyazı" },
      { value: "camliyayla", label: "Çamlıyayla" },
      { value: "erdemli", label: "Erdemli" },
      { value: "gulnar", label: "Gülnar" },
      { value: "mezitli", label: "Mezitli" },
      { value: "mut", label: "Mut" },
      { value: "silifke", label: "Silifke" },
      { value: "tarsus", label: "Tarsus" },
      { value: "toroslar", label: "Toroslar" },
      { value: "yenisehir", label: "Yenişehir" },
    ],
  },
  {
    value: "istanbul",
    label: "İstanbul",
    districts: [
      { value: "adalar", label: "Adalar" },
      { value: "arnavutkoy", label: "Arnavutköy" },
      { value: "atasehir", label: "Ataşehir" },
      { value: "avcilar", label: "Avcılar" },
      { value: "bagcilar", label: "Bağcılar" },
      { value: "bahcelievler", label: "Bahçelievler" },
      { value: "bakirkoy", label: "Bakırköy" },
      { value: "basaksehir", label: "Başakşehir" },
      { value: "bayrampasa", label: "Bayrampaşa" },
      { value: "besiktas", label: "Beşiktaş" },
      { value: "beykoz", label: "Beykoz" },
      { value: "beylikduzu", label: "Beylikdüzü" },
      { value: "beyoglu", label: "Beyoğlu" },
      { value: "buyukcekmece", label: "Büyükçekmece" },
      { value: "catalca", label: "Çatalca" },
      { value: "cekmekoy", label: "Çekmeköy" },
      { value: "esenler", label: "Esenler" },
      { value: "esenyurt", label: "Esenyurt" },
      { value: "eyupsultan", label: "Eyüpsultan" },
      { value: "fatih", label: "Fatih" },
      { value: "gaziosmanpasa", label: "Gaziosmanpaşa" },
      { value: "gungoren", label: "Güngören" },
      { value: "kadikoy", label: "Kadıköy" },
      { value: "kagithane", label: "Kağıthane" },
      { value: "kartal", label: "Kartal" },
      { value: "kucukcekmece", label: "Küçükçekmece" },
      { value: "maltepe", label: "Maltepe" },
      { value: "pendik", label: "Pendik" },
      { value: "sancaktepe", label: "Sancaktepe" },
      { value: "sariyer", label: "Sarıyer" },
      { value: "silivri", label: "Silivri" },
      { value: "sultanbeyli", label: "Sultanbeyli" },
      { value: "sultangazi", label: "Sultangazi" },
      { value: "sile", label: "Şile" },
      { value: "sisli", label: "Şişli" },
      { value: "tuzla", label: "Tuzla" },
      { value: "umraniye", label: "Ümraniye" },
      { value: "uskudar", label: "Üsküdar" },
      { value: "zeytinburnu", label: "Zeytinburnu" },
    ],
  },
  {
    value: "izmir",
    label: "İzmir",
    districts: [
      { value: "aliaga", label: "Aliağa" },
      { value: "balcova", label: "Balçova" },
      { value: "bayindir", label: "Bayındır" },
      { value: "bayrakli", label: "Bayraklı" },
      { value: "bergama", label: "Bergama" },
      { value: "beydag", label: "Beydağ" },
      { value: "bornova", label: "Bornova" },
      { value: "buca", label: "Buca" },
      { value: "cesme", label: "Çeşme" },
      { value: "cigli", label: "Çiğli" },
      { value: "dikili", label: "Dikili" },
      { value: "foca", label: "Foça" },
      { value: "gaziemir", label: "Gaziemir" },
      { value: "guzelbahce", label: "Güzelbahçe" },
      { value: "karaburun", label: "Karaburun" },
      { value: "karsiyaka", label: "Karşıyaka" },
      { value: "kemalpasa", label: "Kemalpaşa" },
      { value: "kinik", label: "Kınık" },
      { value: "kiraz", label: "Kiraz" },
      { value: "konak", label: "Konak" },
      { value: "menderes", label: "Menderes" },
      { value: "menemen", label: "Menemen" },
      { value: "narlidere", label: "Narlıdere" },
      { value: "odemis", label: "Ödemiş" },
      { value: "seferihisar", label: "Seferihisar" },
      { value: "selcuk", label: "Selçuk" },
      { value: "tire", label: "Tire" },
      { value: "torbali", label: "Torbalı" },
      { value: "urla", label: "Urla" },
    ],
  },
  {
    value: "kars",
    label: "Kars",
    districts: [
      { value: "akyaka", label: "Akyaka" },
      { value: "arpacay", label: "Arpaçay" },
      { value: "digor", label: "Digor" },
      { value: "kagizman", label: "Kağızman" },
      { value: "merkez", label: "Merkez" },
      { value: "sarikamis", label: "Sarıkamış" },
      { value: "selim", label: "Selim" },
      { value: "susuz", label: "Susuz" },
    ],
  },
  {
    value: "kastamonu",
    label: "Kastamonu",
    districts: [
      { value: "abana", label: "Abana" },
      { value: "agli", label: "Ağlı" },
      { value: "arac", label: "Araç" },
      { value: "azdavay", label: "Azdavay" },
      { value: "bozkurt", label: "Bozkurt" },
      { value: "cide", label: "Cide" },
      { value: "catalzeytin", label: "Çatalzeytin" },
      { value: "daday", label: "Daday" },
      { value: "devrekani", label: "Devrekâni" },
      { value: "doganyurt", label: "Doğanyurt" },
      { value: "hanonu", label: "Hanönü" },
      { value: "ihsangazi", label: "İhsangazi" },
      { value: "inebolu", label: "İnebolu" },
      { value: "kure", label: "Küre" },
      { value: "merkez", label: "Merkez" },
      { value: "pinarbasi", label: "Pınarbaşı" },
      { value: "seydiler", label: "Seydiler" },
      { value: "senpazar", label: "Şenpazar" },
      { value: "taskopru", label: "Taşköprü" },
      { value: "tosya", label: "Tosya" },
    ],
  },
  {
    value: "kayseri",
    label: "Kayseri",
    districts: [
      { value: "akkisla", label: "Akkışla" },
      { value: "bunyan", label: "Bünyan" },
      { value: "develi", label: "Develi" },
      { value: "felahiye", label: "Felahiye" },
      { value: "hacilar", label: "Hacılar" },
      { value: "incesu", label: "İncesu" },
      { value: "kocasinan", label: "Kocasinan" },
      { value: "melikgazi", label: "Melikgazi" },
      { value: "ozvatan", label: "Özvatan" },
      { value: "pinarbasi", label: "Pınarbaşı" },
      { value: "sarioglan", label: "Sarıoğlan" },
      { value: "sariz", label: "Sarız" },
      { value: "talas", label: "Talas" },
      { value: "tomarza", label: "Tomarza" },
      { value: "yahyali", label: "Yahyalı" },
      { value: "yesilhisar", label: "Yeşilhisar" },
    ],
  },
  {
    value: "kirklareli",
    label: "Kırklareli",
    districts: [
      { value: "babeski", label: "Babaeski" },
      { value: "demirkoy", label: "Demirköy" },
      { value: "kofcaz", label: "Kofçaz" },
      { value: "luleburgaz", label: "Lüleburgaz" },
      { value: "merkez", label: "Merkez" },
      { value: "pehlivankoy", label: "Pehlivanköy" },
      { value: "pinarhisar", label: "Pınarhisar" },
      { value: "vize", label: "Vize" },
    ],
  },
  {
    value: "kirsehir",
    label: "Kırşehir",
    districts: [
      { value: "akcakent", label: "Akçakent" },
      { value: "akpinar", label: "Akpınar" },
      { value: "boztepe", label: "Boztepe" },
      { value: "cicekdagi", label: "Çiçekdağı" },
      { value: "kaman", label: "Kaman" },
      { value: "merkez", label: "Merkez" },
      { value: "mucur", label: "Mucur" },
    ],
  },
  {
    value: "kocaeli",
    label: "Kocaeli",
    districts: [
      { value: "basiskele", label: "Başiskele" },
      { value: "cayirova", label: "Çayırova" },
      { value: "darica", label: "Darıca" },
      { value: "derince", label: "Derince" },
      { value: "dilovasi", label: "Dilovası" },
      { value: "gebze", label: "Gebze" },
      { value: "golcuk", label: "Gölcük" },
      { value: "izmit", label: "İzmit" },
      { value: "kandira", label: "Kandıra" },
      { value: "karamursel", label: "Karamürsel" },
      { value: "kartepe", label: "Kartepe" },
      { value: "korfez", label: "Körfez" },
    ],
  },
  {
    value: "konya",
    label: "Konya",
    districts: [
      { value: "ahirli", label: "Ahırlı" },
      { value: "akoren", label: "Akören" },
      { value: "aksehir", label: "Akşehir" },
      { value: "altinekin", label: "Altınekin" },
      { value: "beysehir", label: "Beyşehir" },
      { value: "bozkir", label: "Bozkır" },
      { value: "cihanbeyli", label: "Cihanbeyli" },
      { value: "celtik", label: "Çeltik" },
      { value: "cumra", label: "Çumra" },
      { value: "derbent", label: "Derbent" },
      { value: "derebucak", label: "Derebucak" },
      { value: "doganhisar", label: "Doğanhisar" },
      { value: "emirgazi", label: "Emirgazi" },
      { value: "eregli", label: "Ereğli" },
      { value: "guneysinir", label: "Güneysınır" },
      { value: "hadim", label: "Hadim" },
      { value: "halkapinar", label: "Halkapınar" },
      { value: "huyuk", label: "Hüyük" },
      { value: "ilgin", label: "Ilgın" },
      { value: "kadinhani", label: "Kadınhanı" },
      { value: "karapinar", label: "Karapınar" },
      { value: "karatay", label: "Karatay" },
      { value: "kulu", label: "Kulu" },
      { value: "meram", label: "Meram" },
      { value: "sarayonu", label: "Sarayönü" },
      { value: "selcuklu", label: "Selçuklu" },
      { value: "seydisehir", label: "Seydişehir" },
      { value: "taskent", label: "Taşkent" },
      { value: "tuzlukcu", label: "Tuzlukçu" },
      { value: "yalihuyuk", label: "Yalıhüyük" },
      { value: "yunak", label: "Yunak" },
    ],
  },
  {
    value: "kutahya",
    label: "Kütahya",
    districts: [
      { value: "altintas", label: "Altıntaş" },
      { value: "aslanapa", label: "Aslanapa" },
      { value: "cavdarhisar", label: "Çavdarhisar" },
      { value: "domainc", label: "Domaniç" },
      { value: "dumlupinar", label: "Dumlupınar" },
      { value: "emet", label: "Emet" },
      { value: "gediz", label: "Gediz" },
      { value: "hisarcik", label: "Hisarcık" },
      { value: "merkez", label: "Merkez" },
      { value: "pazarlar", label: "Pazarlar" },
      { value: "simav", label: "Simav" },
      { value: "saphane", label: "Şaphane" },
      { value: "tavsanli", label: "Tavşanlı" },
    ],
  },
  {
    value: "malatya",
    label: "Malatya",
    districts: [
      { value: "akcadag", label: "Akçadağ" },
      { value: "arapgir", label: "Arapgir" },
      { value: "arguvan", label: "Arguvan" },
      { value: "battalgazi", label: "Battalgazi" },
      { value: "darende", label: "Darende" },
      { value: "dogansehir", label: "Doğanşehir" },
      { value: "doganyol", label: "Doğanyol" },
      { value: "hekimhan", label: "Hekimhan" },
      { value: "kale", label: "Kale" },
      { value: "kuluncak", label: "Kuluncak" },
      { value: "puturge", label: "Pütürge" },
      { value: "yazihan", label: "Yazıhan" },
      { value: "yesilyurt", label: "Yeşilyurt" },
    ],
  },
  {
    value: "manisa",
    label: "Manisa",
    districts: [
      { value: "ahmetli", label: "Ahmetli" },
      { value: "akhisar", label: "Akhisar" },
      { value: "alasehir", label: "Alaşehir" },
      { value: "demirci", label: "Demirci" },
      { value: "golmarmara", label: "Gölmarmara" },
      { value: "gordes", label: "Gördes" },
      { value: "kirkagac", label: "Kırkağaç" },
      { value: "koprubasi", label: "Köprübaşı" },
      { value: "kula", label: "Kula" },
      { value: "salihli", label: "Salihli" },
      { value: "sarigol", label: "Sarıgöl" },
      { value: "saruhanli", label: "Saruhanlı" },
      { value: "selendi", label: "Selendi" },
      { value: "soma", label: "Soma" },
      { value: "sehzadeler", label: "Şehzadeler" },
      { value: "turgutlu", label: "Turgutlu" },
      { value: "yunusemre", label: "Yunusemre" },
    ],
  },
  {
    value: "kahramanmaras",
    label: "Kahramanmaraş",
    districts: [
      { value: "afsin", label: "Afşin" },
      { value: "andirin", label: "Andırın" },
      { value: "caglayancerit", label: "Çağlayancerit" },
      { value: "dulkadiroglu", label: "Dulkadiroğlu" },
      { value: "ekinozu", label: "Ekinözü" },
      { value: "elbistan", label: "Elbistan" },
      { value: "goksun", label: "Göksun" },
      { value: "nurhak", label: "Nurhak" },
      { value: "onikisubat", label: "Onikişubat" },
      { value: "pazarcik", label: "Pazarcık" },
      { value: "turkoglu", label: "Türkoğlu" },
    ],
  },
  {
    value: "mardin",
    label: "Mardin",
    districts: [
      { value: "artuklu", label: "Artuklu" },
      { value: "dargecit", label: "Dargeçit" },
      { value: "derik", label: "Derik" },
      { value: "kiziltepe", label: "Kızıltepe" },
      { value: "mazidagi", label: "Mazıdağı" },
      { value: "midyat", label: "Midyat" },
      { value: "nusaybin", label: "Nusaybin" },
      { value: "omerli", label: "Ömerli" },
      { value: "savur", label: "Savur" },
      { value: "yesilli", label: "Yeşilli" },
    ],
  },
  {
    value: "mugla",
    label: "Muğla",
    districts: [
      { value: "bodrum", label: "Bodrum" },
      { value: "dalaman", label: "Dalaman" },
      { value: "datca", label: "Datça" },
      { value: "fethiye", label: "Fethiye" },
      { value: "kavaklidere", label: "Kavaklıdere" },
      { value: "koycegiz", label: "Köyceğiz" },
      { value: "marmaris", label: "Marmaris" },
      { value: "mentese", label: "Menteşe" },
      { value: "milas", label: "Milas" },
      { value: "ortaca", label: "Ortaca" },
      { value: "seykikemer", label: "Seydikemer" },
      { value: "ula", label: "Ula" },
      { value: "yatagan", label: "Yatağan" },
    ],
  },
  {
    value: "mus",
    label: "Muş",
    districts: [
      { value: "bulanik", label: "Bulanık" },
      { value: "haskoy", label: "Hasköy" },
      { value: "korkut", label: "Korkut" },
      { value: "malazgirt", label: "Malazgirt" },
      { value: "merkez", label: "Merkez" },
      { value: "varto", label: "Varto" },
    ],
  },
  {
    value: "nevsehir",
    label: "Nevşehir",
    districts: [
      { value: "acigol", label: "Acıgöl" },
      { value: "avanos", label: "Avanos" },
      { value: "derinkuyu", label: "Derinkuyu" },
      { value: "gulsehir", label: "Gülşehir" },
      { value: "hacibektas", label: "Hacıbektaş" },
      { value: "kozakli", label: "Kozaklı" },
      { value: "merkez", label: "Merkez" },
      { value: "urgup", label: "Ürgüp" },
    ],
  },
  {
    value: "nigde",
    label: "Niğde",
    districts: [
      { value: "altunhisar", label: "Altunhisar" },
      { value: "bor", label: "Bor" },
      { value: "camardi", label: "Çamardı" },
      { value: "ciftlik", label: "Çiftlik" },
      { value: "merkez", label: "Merkez" },
      { value: "ulukisla", label: "Ulukışla" },
    ],
  },
  {
    value: "ordu",
    label: "Ordu",
    districts: [
      { value: "akkus", label: "Akkuş" },
      { value: "altinordu", label: "Altınordu" },
      { value: "aybasti", label: "Aybastı" },
      { value: "camas", label: "Çamaş" },
      { value: "catalpinar", label: "Çatalpınar" },
      { value: "caybasi", label: "Çaybaşı" },
      { value: "fatsa", label: "Fatsa" },
      { value: "golkoy", label: "Gölköy" },
      { value: "gulyali", label: "Gülyalı" },
      { value: "gurgentepe", label: "Gürgentepe" },
      { value: "ikizce", label: "İkizce" },
      { value: "kabaduz", label: "Kabadüz" },
      { value: "kabatas", label: "Kabataş" },
      { value: "korgan", label: "Korgan" },
      { value: "kumru", label: "Kumru" },
      { value: "mesudiye", label: "Mesudiye" },
      { value: "persembe", label: "Perşembe" },
      { value: "ulubey", label: "Ulubey" },
      { value: "uny", label: "Ünye" },
    ],
  },
  {
    value: "rize",
    label: "Rize",
    districts: [
      { value: "ardesen", label: "Ardeşen" },
      { value: "camilhemsin", label: "Çamlıhemşin" },
      { value: "cayeli", label: "Çayeli" },
      { value: "derepazari", label: "Derepazarı" },
      { value: "findikli", label: "Fındıklı" },
      { value: "guneysu", label: "Güneysu" },
      { value: "hemsin", label: "Hemşin" },
      { value: "ikizdere", label: "İkizdere" },
      { value: "iyidere", label: "İyidere" },
      { value: "kalkandere", label: "Kalkandere" },
      { value: "merkez", label: "Merkez" },
      { value: "pazar", label: "Pazar" },
    ],
  },
  {
    value: "sakarya",
    label: "Sakarya",
    districts: [
      { value: "adapazari", label: "Adapazarı" },
      { value: "akyazi", label: "Akyazı" },
      { value: "arifiye", label: "Arifiye" },
      { value: "erenler", label: "Erenler" },
      { value: "ferizli", label: "Ferizli" },
      { value: "geyve", label: "Geyve" },
      { value: "hendek", label: "Hendek" },
      { value: "karapurcek", label: "Karapürçek" },
      { value: "karasu", label: "Karasu" },
      { value: "kaynarca", label: "Kaynarca" },
      { value: "kocaali", label: "Kocaali" },
      { value: "pamukova", label: "Pamukova" },
      { value: "sapanca", label: "Sapanca" },
      { value: "serdivan", label: "Serdivan" },
      { value: "sogutlu", label: "Söğütlü" },
      { value: "tarakli", label: "Taraklı" },
    ],
  },
  {
    value: "samsun",
    label: "Samsun",
    districts: [
      { value: "alacam", label: "Alaçam" },
      { value: "asarcik", label: "Asarcık" },
      { value: "atakum", label: "Atakum" },
      { value: "ayvacik", label: "Ayvacık" },
      { value: "bafra", label: "Bafra" },
      { value: "canik", label: "Canik" },
      { value: "carsamba", label: "Çarşamba" },
      { value: "havza", label: "Havza" },
      { value: "ilkadim", label: "İlkadım" },
      { value: "kavak", label: "Kavak" },
      { value: "ladik", label: "Ladik" },
      { value: "ondokuzmayis", label: "Ondokuzmayıs" },
      { value: "salipazari", label: "Salıpazarı" },
      { value: "tekekoy", label: "Tekkeköy" },
      { value: "terme", label: "Terme" },
      { value: "vezirkopru", label: "Vezirköprü" },
      { value: "yakakent", label: "Yakakent" },
    ],
  },
  {
    value: "siirt",
    label: "Siirt",
    districts: [
      { value: "baykan", label: "Baykan" },
      { value: "eruh", label: "Eruh" },
      { value: "kurtalan", label: "Kurtalan" },
      { value: "merkez", label: "Merkez" },
      { value: "pervari", label: "Pervari" },
      { value: "sirvan", label: "Şirvan" },
      { value: "tillo", label: "Tillo" },
    ],
  },
  {
    value: "sinop",
    label: "Sinop",
    districts: [
      { value: "ayancik", label: "Ayancık" },
      { value: "boyabat", label: "Boyabat" },
      { value: "dikmen", label: "Dikmen" },
      { value: "duragan", label: "Durağan" },
      { value: "erfelek", label: "Erfelek" },
      { value: "gerze", label: "Gerze" },
      { value: "merkez", label: "Merkez" },
      { value: "sarayduzu", label: "Saraydüzü" },
      { value: "turkeli", label: "Türkeli" },
    ],
  },
  {
    value: "sivas",
    label: "Sivas",
    districts: [
      { value: "akincilar", label: "Akıncılar" },
      { value: "altinyayla", label: "Altınyayla" },
      { value: "divrigi", label: "Divriği" },
      { value: "dogansehir", label: "Doğanşar" },
      { value: "gemerek", label: "Gemerek" },
      { value: "golova", label: "Gölova" },
      { value: "gurun", label: "Gürün" },
      { value: "hafik", label: "Hafik" },
      { value: "imranli", label: "İmranlı" },
      { value: "kangal", label: "Kangal" },
      { value: "koyulhisar", label: "Koyulhisar" },
      { value: "merkez", label: "Merkez" },
      { value: "susehri", label: "Suşehri" },
      { value: "sarkisla", label: "Şarkışla" },
      { value: "ulas", label: "Ulaş" },
      { value: "yildizeli", label: "Yıldızeli" },
      { value: "zara", label: "Zara" },
    ],
  },
  {
    value: "tekirdag",
    label: "Tekirdağ",
    districts: [
      { value: "cerkezkoy", label: "Çerkezköy" },
      { value: "corlu", label: "Çorlu" },
      { value: "ergene", label: "Ergene" },
      { value: "hayrabolu", label: "Hayrabolu" },
      { value: "kapakli", label: "Kapaklı" },
      { value: "malkara", label: "Malkara" },
      { value: "marmaraereg", label: "Marmaraereğlisi" },
      { value: "muratli", label: "Muratlı" },
      { value: "saray", label: "Saray" },
      { value: "suleymanpasa", label: "Süleymanpaşa" },
      { value: "sarkoy", label: "Şarköy" },
    ],
  },
  {
    value: "tokat",
    label: "Tokat",
    districts: [
      { value: "almus", label: "Almus" },
      { value: "artova", label: "Artova" },
      { value: "basciftlik", label: "Başçiftlik" },
      { value: "erbaa", label: "Erbaa" },
      { value: "merkez", label: "Merkez" },
      { value: "niksar", label: "Niksar" },
      { value: "pazar", label: "Pazar" },
      { value: "resadiye", label: "Reşadiye" },
      { value: "sulusaray", label: "Sulusaray" },
      { value: "turhal", label: "Turhal" },
      { value: "yesilyurt", label: "Yeşilyurt" },
      { value: "zile", label: "Zile" },
    ],
  },
  {
    value: "trabzon",
    label: "Trabzon",
    districts: [
      { value: "akcaabat", label: "Akçaabat" },
      { value: "arakli", label: "Araklı" },
      { value: "arsin", label: "Arsin" },
      { value: "besikduzu", label: "Beşikdüzü" },
      { value: "carsibasi", label: "Çarşıbaşı" },
      { value: "caykara", label: "Çaykara" },
      { value: "dernekpazari", label: "Dernekpazarı" },
      { value: "duzkoy", label: "Düzköy" },
      { value: "hayrat", label: "Hayrat" },
      { value: "koprubasi", label: "Köprübaşı" },
      { value: "macka", label: "Maçka" },
      { value: "of", label: "Of" },
      { value: "ortahisar", label: "Ortahisar" },
      { value: "surmene", label: "Sürmene" },
      { value: "salpazari", label: "Şalpazarı" },
      { value: "tonya", label: "Tonya" },
      { value: "vakfikebir", label: "Vakfıkebir" },
      { value: "yomra", label: "Yomra" },
    ],
  },
  {
    value: "tunceli",
    label: "Tunceli",
    districts: [
      { value: "cemisgezek", label: "Çemişgezek" },
      { value: "hocat", label: "Hozat" },
      { value: "mazgirt", label: "Mazgirt" },
      { value: "merkez", label: "Merkez" },
      { value: "nazimiye", label: "Nazımiye" },
      { value: "ovacik", label: "Ovacık" },
      { value: "pertek", label: "Pertek" },
      { value: "pulumur", label: "Pülümür" },
    ],
  },
  {
    value: "sanliurfa",
    label: "Şanlıurfa",
    districts: [
      { value: "akcakale", label: "Akçakale" },
      { value: "birecik", label: "Birecik" },
      { value: "bozova", label: "Bozova" },
      { value: "ceylanpinar", label: "Ceylanpınar" },
      { value: "eyyubiye", label: "Eyyübiye" },
      { value: "halfeti", label: "Halfeti" },
      { value: "haliliye", label: "Haliliye" },
      { value: "harran", label: "Harran" },
      { value: "hilvan", label: "Hilvan" },
      { value: "karakopru", label: "Karaköprü" },
      { value: "siverek", label: "Siverek" },
      { value: "suruc", label: "Suruç" },
      { value: "viransehir", label: "Viranşehir" },
    ],
  },
  {
    value: "usak",
    label: "Uşak",
    districts: [
      { value: "banaz", label: "Banaz" },
      { value: "esme", label: "Eşme" },
      { value: "karahalli", label: "Karahallı" },
      { value: "merkez", label: "Merkez" },
      { value: "sivasli", label: "Sivaslı" },
      { value: "ulubey", label: "Ulubey" },
    ],
  },
  {
    value: "van",
    label: "Van",
    districts: [
      { value: "bahcesaray", label: "Bahçesaray" },
      { value: "baskale", label: "Başkale" },
      { value: "caldiran", label: "Çaldıran" },
      { value: "catak", label: "Çatak" },
      { value: "edremit", label: "Edremit" },
      { value: "ercis", label: "Erciş" },
      { value: "gevas", label: "Gevaş" },
      { value: "gurpinar", label: "Gürpınar" },
      { value: "ipekyolu", label: "İpekyolu" },
      { value: "muradiye", label: "Muradiye" },
      { value: "ozalp", label: "Özalp" },
      { value: "saray", label: "Saray" },
      { value: "tusba", label: "Tuşba" },
    ],
  },
  {
    value: "yozgat",
    label: "Yozgat",
    districts: [
      { value: "akdagmadeni", label: "Akdağmadeni" },
      { value: "aydincik", label: "Aydıncık" },
      { value: "bogazliyan", label: "Boğazlıyan" },
      { value: "candir", label: "Çandır" },
      { value: "cayiralan", label: "Çayıralan" },
      { value: "cekerek", label: "Çekerek" },
      { value: "kadisehri", label: "Kadışehri" },
      { value: "merkez", label: "Merkez" },
      { value: "saraykent", label: "Saraykent" },
      { value: "sarikaya", label: "Sarıkaya" },
      { value: "sorgun", label: "Sorgun" },
      { value: "sefaatli", label: "Şefaatli" },
      { value: "yenifakili", label: "Yenifakılı" },
      { value: "yerkoy", label: "Yerköy" },
    ],
  },
  {
    value: "zonguldak",
    label: "Zonguldak",
    districts: [
      { value: "alapi", label: "Alaplı" },
      { value: "caycuma", label: "Çaycuma" },
      { value: "devrek", label: "Devrek" },
      { value: "eregli", label: "Ereğli" },
      { value: "gokcebey", label: "Gökçebey" },
      { value: "kilimli", label: "Kilimli" },
      { value: "kozluk", label: "Kozlu" },
      { value: "merkez", label: "Merkez" },
    ],
  },
  {
    value: "aksaray",
    label: "Aksaray",
    districts: [
      { value: "agacoren", label: "Ağaçören" },
      { value: "eskil", label: "Eskil" },
      { value: "gulagac", label: "Gülağaç" },
      { value: "guzelyurt", label: "Güzelyurt" },
      { value: "merkez", label: "Merkez" },
      { value: "ortakoy", label: "Ortaköy" },
      { value: "sariyahsi", label: "Sarıyahşi" },
      { value: "sultanhani", label: "Sultanhanı" },
    ],
  },
  {
    value: "bayburt",
    label: "Bayburt",
    districts: [
      { value: "aydintepe", label: "Aydıntepe" },
      { value: "demirozu", label: "Demirözü" },
      { value: "merkez", label: "Merkez" },
    ],
  },
  {
    value: "karaman",
    label: "Karaman",
    districts: [
      { value: "ayranci", label: "Ayrancı" },
      { value: "basyayla", label: "Başyayla" },
      { value: "ermenek", label: "Ermenek" },
      { value: "kazimkarabekir", label: "Kazımkarabekir" },
      { value: "merkez", label: "Merkez" },
      { value: "sariveliler", label: "Sarıveliler" },
    ],
  },
  {
    value: "kirikkale",
    label: "Kırıkkale",
    districts: [
      { value: "bahsili", label: "Bahşılı" },
      { value: "baliseyh", label: "Balışeyh" },
      { value: "celebi", label: "Çelebi" },
      { value: "delice", label: "Delice" },
      { value: "karakecili", label: "Karakeçili" },
      { value: "keskin", label: "Keskin" },
      { value: "merkez", label: "Merkez" },
      { value: "sulakyurt", label: "Sulakyurt" },
      { value: "yahsihan", label: "Yahşihan" },
    ],
  },
  {
    value: "batman",
    label: "Batman",
    districts: [
      { value: "besiri", label: "Beşiri" },
      { value: "gercus", label: "Gercüş" },
      { value: "hasankeyf", label: "Hasankeyf" },
      { value: "kozluk", label: "Kozluk" },
      { value: "merkez", label: "Merkez" },
      { value: "sason", label: "Sason" },
    ],
  },
  {
    value: "sirnak",
    label: "Şırnak",
    districts: [
      { value: "beytussebap", label: "Beytüşşebap" },
      { value: "cizre", label: "Cizre" },
      { value: "guclukonak", label: "Güçlükonak" },
      { value: "idil", label: "İdil" },
      { value: "merkez", label: "Merkez" },
      { value: "silopi", label: "Silopi" },
      { value: "uludere", label: "Uludere" },
    ],
  },
  {
    value: "bartin",
    label: "Bartın",
    districts: [
      { value: "amasra", label: "Amasra" },
      { value: "kurucasile", label: "Kurucaşile" },
      { value: "merkez", label: "Merkez" },
      { value: "ulus", label: "Ulus" },
    ],
  },
  {
    value: "ardahan",
    label: "Ardahan",
    districts: [
      { value: "cildir", label: "Çıldır" },
      { value: "damal", label: "Damal" },
      { value: "gole", label: "Göle" },
      { value: "hanak", label: "Hanak" },
      { value: "merkez", label: "Merkez" },
      { value: "posof", label: "Posof" },
    ],
  },
  {
    value: "igdir",
    label: "Iğdır",
    districts: [
      { value: "aralik", label: "Aralık" },
      { value: "karakoyunlu", label: "Karakoyunlu" },
      { value: "merkez", label: "Merkez" },
      { value: "tuzluca", label: "Tuzluca" },
    ],
  },
  {
    value: "yalova",
    label: "Yalova",
    districts: [
      { value: "altinova", label: "Altınova" },
      { value: "armutlu", label: "Armutlu" },
      { value: "cinarcik", label: "Çınarcık" },
      { value: "ciftlikkoy", label: "Çiftlikköy" },
      { value: "merkez", label: "Merkez" },
      { value: "termal", label: "Termal" },
    ],
  },
  {
    value: "karabuk",
    label: "Karabük",
    districts: [
      { value: "eflani", label: "Eflani" },
      { value: "eskipazar", label: "Eskipazar" },
      { value: "merkez", label: "Merkez" },
      { value: "ovacik", label: "Ovacık" },
      { value: "safranbolu", label: "Safranbolu" },
      { value: "yenice", label: "Yenice" },
    ],
  },
  {
    value: "kilis",
    label: "Kilis",
    districts: [
      { value: "elbeyli", label: "Elbeyli" },
      { value: "merkez", label: "Merkez" },
      { value: "musabeyli", label: "Musabeyli" },
      { value: "polateli", label: "Polateli" },
    ],
  },
  {
    value: "osmaniye",
    label: "Osmaniye",
    districts: [
      { value: "bahce", label: "Bahçe" },
      { value: "duzici", label: "Düziçi" },
      { value: "hasanbeyli", label: "Hasanbeyli" },
      { value: "kadirli", label: "Kadirli" },
      { value: "merkez", label: "Merkez" },
      { value: "sumbas", label: "Sumbas" },
      { value: "toprakkale", label: "Toprakkale" },
    ],
  },
  {
    value: "duzce",
    label: "Düzce",
    districts: [
      { value: "akcakoca", label: "Akçakoca" },
      { value: "cumayeri", label: "Cumayeri" },
      { value: "cilimli", label: "Çilimli" },
      { value: "golyaka", label: "Gölyaka" },
      { value: "gumusova", label: "Gümüşova" },
      { value: "kaynasli", label: "Kaynaşlı" },
      { value: "merkez", label: "Merkez" },
      { value: "yigilca", label: "Yığılca" },
    ],
  },
];

/** Flattened list of all cities as ComboboxOption (without districts). */
export const CITY_OPTIONS = TURKEY_CITIES.map((c) => ({
  value: c.value,
  label: c.label,
}));

/**
 * Returns the district options for a given city value.
 * Returns empty array if city not found.
 */
export function getDistrictsByCity(cityValue: string) {
  const city = TURKEY_CITIES.find((c) => c.value === cityValue);
  return city?.districts ?? [];
}

/** Find a city label by its value. */
export function getCityLabel(cityValue: string): string | undefined {
  return TURKEY_CITIES.find((c) => c.value === cityValue)?.label;
}

/** Find a district label by city value and district value. */
export function getDistrictLabel(cityValue: string, districtValue: string): string | undefined {
  const city = TURKEY_CITIES.find((c) => c.value === cityValue);
  return city?.districts.find((d) => d.value === districtValue)?.label;
}
